name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    container: sautoirs/rosary:0.3.0

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Init CMake directory
      run: cmake -S . -B build -G Ninja
    - name: Configure CMake directory
      run: cmake build -DBUILD_TESTING=ON
    - name: Build project
      run: cmake --build build
    - name: Run tests
      run: ./build/tests/unit/Runner
    - name: Upload coverage to codecov
      run: bash <(curl -s https://codecov.io/bash)
      shell: bash
      working-directory: build
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

